# Generated by Django 3.1.7 on 2021-05-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_agent_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='slug',
            field=models.SlugField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
