# Generated by Django 3.1.7 on 2021-05-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_remove_agent_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='slug',
            field=models.SlugField(default='allison', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
