# Generated by Django 3.1.7 on 2021-04-07 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_auto_20210407_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
